### ISSUE TITLE
Tall Matrix multiplication with a column matrix with CPU(FMat) vs GPU(GMat) : GPU not caching matrix

### ISSUE THREAD

**Issue by shethsh** [BIDData/BIDMat#53]
I am trying to identify the top 10 similar, say,

 documents from a list of 2.7 Million documents for a new document that I get. Each document is represented as a vector of 500 doubles. The number of documents is 2,633,142. So, we have a matrix of size gc = (2633142 x 500) for all the processed documents. Whenever a new document arrives, we compute it's vector e = (500 x 1). Assuming that the vectors are normalized, we need to compute the dot product of e with each row of gc and pick the maximum value from the resulting matrix(2,633,142 x 1).
When I compute the dot product of a new document features with that of 2.7 million images' features using BIDMach matrix matrix multiplication, it takes 300 milliseconds using FMat and 1200 milliseonds using GMat. I am attaching the screenshot. I was expecting GMat to work faster than FMat. Another thing I observe is that the amount of GPU memory used while creating GMat is less than 100 MBs while I was expecting it to use 3 GB. Looks like it is not caching the Matrix in GPU memory which is leading to slower execution. Can you tell me if I am doing something wrong here or whether any kind of improvement can be done to cache the data properly in memory and reduce the time consumption of GMat based matrix multiplication?

The computation is a matrix multiplication of dimensions:
(2633142 x 500) * (500 x 1) = (2633142 x 1)

I don't understand why CPU is faster than GPU and how to obtain faster speed with GPU, say, in a few 100 milliseconds.
[Notebook.pdf](https://github.com/BIDData/BIDMat/files/93047/Notebook.pdf)

**Comment by jcanny** [comment]
Your matrix is more than a billion elements which is pushing the limits of what the GPU can handle. GMats can actually be stored in CPU memory, and we have a threshold which moves them to CPU memory when they're very big. Unfortunately this is much slower. However, your matrix can probably still fit in the memory of newer GPUs. The variable that controls this is Mat.hostAllocSize. I increased it so it will store matrices up to 2 billion elements on the GPU. 2 billion is the limit for Java and things get difficult if matrices have more than that. With that change, the time for your matrix operation drops to about 30 milliseconds on a K40 GPU. 

btw, if you can manage to group a few of your vectors together it will be *much* faster. Matrix-vector multiply is memory bound (each matrix element is used only once) and doesnt allow the GPU to do much work. Matrix-matrix multiply operations are much faster since each matrix element is used many times. 

Not sure you need caching. If you're reusing your large matrix it will just live in GPU memory. You would only need caching for the vectors. If you're running inside the Learner framework, it gets turned on and off automatically. Otherwise you need to set Mat.useCache = true.

**Comment by shethsh** [comment]
Hi John,
Thanks for the quick response. I now understand the problem.
I was able to increase the hostAllocSize and I am able to cache data upto 2 Million rows with GPU0.
Thanks again.

Next part:
The host I am using is a g2.8large node on EC2 and has four GPUs. I want to cache 2 million * 4 = 8 million on these four GPUs by splitting the data into four equal chunks of 2 million rows. When I try to cache the next matrix of 2 million rows, it gives me an error saying:
java.lang.RuntimeException: CUDA alloc failed out of memory
    BIDMat.GMat$.apply(GMat.scala:1713)
    BIDMat.GMat$.newOrCheckGMat(GMat.scala:2482)
    BIDMat.GMat$.newOrCheckGMat(GMat.scala:2523)
    BIDMat.GMat$.apply(GMat.scala:1719)

Looks like it is trying to cache it again in GPU0 which is almost full, but, GPU1 has  a lot of free RAM.

How do I explicitly cache 4 different matrices on this single g2.8xlarge node on the four GPUs and then, compute the matrix multiplication of a single column matrix with all these four cached matrices? Also, can I perform these four matrix multiplications parallelly?
I want something like this - 
a1 - FMat with size (2,000,000, 500)
a2 - FMat with size (2,000,000, 500)
a3 - FMat with size (2,000,000, 500)
a4 - FMat with size (2,000,000, 500)

g1 = GMat(a1) // to be cached on GPU 0
g2 = GMat(a2) // to be cached on GPU 1
g3 = GMat(a3) // to be cached on GPU 2
g4 = GMat(a4) // to be cached on GPU 3

val e1 = e
val e2 = e
val e3 = e
val e4 = e
(i.e. e1=e2=e3=e4 which are of size (500, 1))
In real time, we get a new vector, e of size (500,1)
we need to perform 
1) g1*e1
2) g2*e2
3) g3*e3
4) g4*e4

My questions are:
1) How to ensure that g1 gets cached in GPU0, g2 gets cached in GPU1, g3 gets cached in GPU2 and g4 gets cached in GPU3 ?
2) How to perform parallel computation of g1*e1, g2*e2, g3*e3 and g4*e4 assuming that g1, g2, g3 and g4 are cached in four different GPUs by question 1 above

**Comment by jcanny** [comment]
This is doable, but complicated. CUDA includes thread-local variables that affect the GPUs state. You can set the current working GPU with "setGPU(i)", with i in 0,..,3 on the g2.8xlarge instances. Then any data allocated from that point will be on that GPU. When you retrieve data from a GMat, you will also need to set the GPU to the one on which that matrix was allocated (there are some exceptions to this because you can "connect" two GPUs, but they're not connected by default). btw, each GPU matrix  carries around the identity of its GPU in mat.myGPU. 

If you're using multiple GPUs from different threads, you wont need to do this. Each thread can be associated with just one GPU (do setGPU soon after you create the thread), and data sent from CPU to that GPU will be in its own GPU. 

This is very similar to what the "ParLearner" classes do. Data comes in minibatches and is sent to all the GPUs, each of which is running on its own thread. The difference though is that ParLearner assumes data parallelism only, so each minibatch is sent to just one GPU. 

btw, there is no need to cache g1...g4. Matrices allocated on GPUs are persisted there until you clear the GPU memory. You may want to cache the results of g * e1..e4, although they are very small and it may not matter. What caching does it to *reuse* the storage associated with a matrix. If you have a loop

for (i <- 0 until n) {
   h1 = g1 * e1
}
Then by default a new h1 is generated on each iteration. But if caching is on *and* h1 points to the result of g1 * e1 from a previous iteration *and* g1 and e1 are the same matrices as in the previous iteration (the same containers, not the same contents), then h1 will be reused. Assuming your data is coming from a cpu vector u, then on the first iteration do:

val e1 = GMat(u)

and then 

e1 <-- u

which guarantees that the same container is used for e1 each time, even if u points to a different matrix.

**Comment by shethsh** [comment]
Hi John,
Thanks for the reply. 

I tried caching and reusing the containers as you described above. It seems that there is still incremental memory consumption happening in each iteration at the Matrix multiplication step.
I am attaching the notebook I am using. We can clearly see at the end of the notebook, that GPU memory consumption is increasing in all the 4 GPUs for each iteration. I verified that this is happening at the matrix multiplication line : "mul_result0 = gmat0*vec_gpu0" for GPU0 and so on.
Can you let me know if I am doing some mistake while reusing containers with "<--" ?
How do I use this kind of system where it should be able to run for thousands or millions of iterations without incremental memory consumption?


Data and operations that need to be performed are:
Static data is "gmat0" of size (230,000,4096) which is read once from disk and cached in GPU

For each iteration, we get a new vector, "vec_gpu0" of size(4096,1) from filesystem
and we need to compute the matrix multiplication, gmat0*vec_gpu0 and sort the multiplication result to choose the largest 10 values
[Notebook_bidm.pdf](https://github.com/BIDData/BIDMat/files/106608/Notebook_bidm.pdf)



Thanks and Regards,
Suraj Sheth

**Comment by jcanny** [comment]
Caching works on computation DAGs when all the source nodes are the same between iterations. 

In your code:

vec_cpu0 = FMat(4096,1,filedata)

this will be a new matrix (a new container) on each iteration. Its a source node (doesnt depend on any other nodes). You should not allocate new source nodes in a loop. When you do

vec_gpu0 = GMat(vec_cpu0)

you will also get a new container because it depends on vec_cpu0.

If you instead allocate vec_cpu0 outside the loop and do loadFMat(testfilename, vec_cpu0), the data would have been loaded straight into the same container. 

You could have also done:

vec_cpu0(?) = FMat(4096,1,filedata)

or

vec_cpu0 <-- FMat(4096,1,filedata)

both of which copy a newly-created matrix in the vec_cpu0 container. The its dependency vec_gpu0 will be the same container as well. 

You could have also allocated vec_gpu0 outside the loop and done:

vec_cpu0 = FMat(4096,1,filedata)
vec_gpu0 <-- vec_cpu0

which creates a new vec_cpu0 each time through the loop but copies its contents to the same vec_gpu0. The cpu matrices will be handled by the garbage collector, while the GPU matrices will be cached.

**Comment by jcanny** [comment]
btw, you dont need to allocate cached values explicitly. i.e. your source matrices are vec_cpu0 and gmat0 but the others can be allocated inside the loop:

gpu_num=0;
setGPU(gpu_num)
loadFMat(mat_name, vec_cpu0)
val vec_gpu0 = GMat(vec_cpu0)
val mul_result0 = gmat0 * vec_gpu0
val (svals, inds) = sortdown2(mul_result0)
for (i <- 0 to 9) 
 results(i+gpu_num*10) = (svals(i,0), inds(i,0), text...

**Comment by shethsh** [comment]
Hi John,
Thanks for the solution. 
I confirmed that using 
vec_cpu0(?) = FMat(4096,1,filedata)
 instead of 
vec_cpu0 = FMat(4096,1,filedata)
 works. 
It reuses the same container with this change and this solved the problem.

Thanks and Regards,
Suraj Sheth
